### PR TITLE
Adds MUX and RS-232 level shifter symbols

### PR DESCRIPTION
**Pull request by ammarsubei**

### CODE REVIEW

**Comment by sabinoj** [comment]
Ammar, you need to re-open your symbols and do a "Symbol Translate" to center them out. Right now they are a far way from the mouse when selected from the list.

**Comment by ammarsubei** [comment]
I fixed them, and force pushed. The mistake no longer exists. We're all good now.

**Comment by sabinoj** [comment]
Let me check it.

**Comment by sabinoj** [comment]
I can't seem to pull it. I'm getting this error: 

remote: Counting objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 2), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/ammarsubei/gEDA_Symbols
- branch            master     -> FETCH_HEAD
  Auto-merging PI5C3303TEX.sym
  CONFLICT (add/add): Merge conflict in PI5C3303TEX.sym
  Auto-merging MAX13223E.sym
  CONFLICT (add/add): Merge conflict in MAX13223E.sym
  Automatic merge failed; fix conflicts and then commit the result.

**Comment by l0g1x** [comment]
You have a merge conflict, open up the file and delete what you don’t want. It means you have local changes you made (maybe unintentionally) and they’re on the same line as changes that ammar made.

**Comment by sabinoj** [comment]
Ah, so I just need to "git rm" the files I got from Ammar's repository and I should be able to pull again?

**Comment by bsubei** [comment]
no. So what happened is that you pulled Ammar's changes, which he then force pushed new stuff onto. So now there's 2 conflicting versions.

The fix is to (hard) reset back to before Ammar's pull request. Then, pull his pull request changes again.

**Comment by bsubei** [comment]
`git reset --hard 3169440e05c55c4c87cdeae4f1d7927dce38eb53` then `git pull <ammar's fork> master`

**Comment by sabinoj** [comment]
Thanks, guys, that did it. I'll test these symbols now.

**Comment by sabinoj** [comment]
Ammar, 
Neither symbol has no attributes. By this I mean (at a minimum) a refdes or a device.
You will have to correct those before I can accept your pull request.

**Comment by sabinoj** [comment]
I'm going to grab some food right now, I'll be back to check it in about ten to fifteen minutes.

**Pull request closed without merging**
